title: Karate Braga
description: Karate Braga official website.
url: https://www.karatebraga.com

# OpenGraph defaults
og_image: https://raw.githubusercontent.com/karatebraga/karatebraga.github.io/main/images/logo2.jpg

exclude:
  - .dist
  - README.md
  - vendor
  - vendor/bundle
  - _site
