title: Karate Braga
description: Karate Braga official website.
url: https://www.karatebraga.com

# OpenGraph defaults
og_image: https://raw.githubusercontent.com/karatebraga/karatebraga.github.io/main/images/logo2.jpg

# Footer defaults (can be overridden per-page)
footer_text_pt: "Semin√°rio confirmado! 10 e 11 de Junho 2023"
footer_text_en: "Seminar confirmed! 10th and 11th of June 2023"

exclude:
  - .dist
  - README.md
